### ISSUE TITLE
Glibc failes to configure

### ISSUE THREAD

**Issue by hellobbn** [unikernelLinux/ukl#22]
I am trying to build following the instructions in README.md and it fails when running `configure` for `glibc` with the following config.log:
```
configure:2637: gcc -c -g -O2 -fthread-jumps -mcmodel=kernel -mno-red-zone  -UUKL_BP  conftest.c >&5
cc1: error: code model kernel does not support PIC mode
configure:2641: $? = 1
configure: failed program was:
| /* confdefs.h */
| #define PACKAGE_NAME "GNU C Library"
| #define PACKAGE_TARNAME "glibc"
| #define PACKAGE_VERSION "(see version.h)"
| #define PACKAGE_STRING "GNU C Library (see version.h)"
| #define PACKAGE_BUGREPORT "https://sourceware.org/bugzilla/"
| #define PACKAGE_URL "https://www.gnu.org/software/glibc/"
| #define PKGVERSION "(GNU libc) "
| #define REPORT_BUGS_TO "<https://www.gnu.org/software/libc/bugs.html>"
| /* end confdefs.h.  */
| 
| int
| main ()
| {
| 
|   ;
|   return 0;
| }
configure:2655: error: in `/home/bbn/Documents/UKL/ukl/glibc-build':
configure:2657: error: cannot compute suffix of object files: cannot compile
See `config.log' for more details
```

From what I can tell from google search, should I add `-fno-pie` to the CFLAGS?

Thanks.

**Comment by rwmjones** [comment]
Does adding `-fno-pic` work?

I'm a bit surprised by several aspects of this.  Firstly it doesn't seem like you're using `-fPIC` at all in the command.  However GCC can be built so it uses pic/pie by default, maybe that's what happening here.  What distro is this?

Secondly I'm surprised that the kernel model doesn't support PIC, since I would assume that KASLR would require that.

**Comment by hellobbn** [comment]
> Does adding `-fno-pic` work?
There seems to have some issues with linking.
> 
> I'm a bit surprised by several aspects of this. Firstly it doesn't seem like you're using `-fPIC` at all in the command. However GCC can be built so it uses pic/pie by default, maybe that's what happening here. What distro is this?
> 
> Secondly I'm surprised that the kernel model doesn't support PIC, since I would assume that KASLR would require that.

I am using Archlinux.
If I use `make -j$(nproc)`, then gcc and glibc seem to be built at the same time. Is that correct or does is there any dependence chain like glibc should be built after gcc? I am now testing with `make -j1` so it compiles gcc first. If that does not work, I am going to try if ubuntu or debian works out for me.

System Information:
- Linux kernel: 
`Linux bbnserver 6.0.5-arch1-1 #1 SMP PREEMPT_DYNAMIC Wed, 26 Oct 2022 15:25:45 +0000 x86_64 GNU/Linux`

- GCC:
```
❯ gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-pc-linux-gnu/12.2.0/lto-wrapper
Target: x86_64-pc-linux-gnu
Configured with: /build/gcc/src/gcc/configure --enable-languages=c,c++,ada,fortran,go,lto,objc,obj-c++,d --enable-bootstrap --prefix=/usr --libdir=/usr/lib --libexecdir=/usr/lib --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=https://bugs.archlinux.org/ --with-build-config=bootstrap-lto --with-linker-hash-style=gnu --with-system-zlib --enable-__cxa_atexit --enable-cet=auto --enable-checking=release --enable-clocale=gnu --enable-default-pie --enable-default-ssp --enable-gnu-indirect-function --enable-gnu-unique-object --enable-libstdcxx-backtrace --enable-link-serialization=1 --enable-linker-build-id --enable-lto --enable-multilib --enable-plugin --enable-shared --enable-threads=posix --disable-libssp --disable-libstdcxx-pch --disable-werror
Thread model: posix
Supported LTO compression algorithms: zlib zstd
gcc version 12.2.0 (GCC) 
```
It does have "--enable-default-pie" as a configure option

**Comment by rwmjones** [comment]
I believe there should be no dependency between glibc & libgcc, but I'm not absolutely sure.  @khers would know.

**Comment by hellobbn** [comment]
Thanks, it compiles and boots with `-fno-PIE` for glibc and the hello-world app.
```
[   23.670852] Run /init as init process
hello, from the UKL world
```

**Comment by khers** [comment]
When building on debian based distro, I had to add -fno-PIE, but this seems to break Fedora. We should probably handle it in our configure script

**Comment by rwmjones** [comment]
It's a difference in default configuration of GCC across distros.  See also this exchange: https://lists.fedoraproject.org/archives/list/devel@lists.fedoraproject.org/thread/ID4ZLQ2W2W5TZDTJEFPLCX4LX2N4CO75/#6IKH5FQU6YYIHQ6S4GIPZGCJ3WOFBSJG

I'm surprised that -fno-PIE didn't work on Fedora, but maybe there's some other subtle problem.  It should be possible to detect if GCC (or more generally, the current compiler) creates PIC/PIE objects by default.  I wonder if autoconf-archive already has a test for this ...
