### ISSUE TITLE
No information on licensing

### ISSUE THREAD

**Issue by mikehearn** [unikernelLinux/ukl#27]
Neither the README nor the paper mention licensing. Is it valid to assume that only GPL-compatible software can be run using UKL, i.e. anything run this way must be released under the GPL or a compatible license, unlike in 'real' userspace?

**Comment by rwmjones** [comment]
The application code is linked to the Linux kernel, so the license of the resulting binary will be GPLv2 and you should obey the terms of the GPL when distributing the binary.

**Comment by mikehearn** [comment]
Yes, that's what I thought. However, that would not apply if using UKL purely inside an organization, right? 

Although this is obvious if you know enough about the kernel's interpretation of the GPL, it's probably worth noting that somewhere in the docs or README to avoid anyone being surprised. Currently UKL is pitched purely as a performance upgrade, and it's not a-priori obvious that changing a syscall instruction to a call instruction would have any licensing impact. Also UKL itself is listed as being under the LGPL.

**Comment by khers** [comment]
I am hesitant to declare what is within your rights WRT the GPL and you would need to discuss that with an attorney. The UKL code written by our group is covered by the LGPL except when it is changes to existing projects. In the case where we are altering existing projects, we use the same license as the project we are changing.
