### ISSUE TITLE
'make run' fails with missing min-initd.d/root

### ISSUE THREAD

**Issue by mshindo** [unikernelLinux/ukl#8]
I followed the instruction written in the "An example of Linux unikernel: TCP echo server" section. Then I get the following error when I run "make run" command:

`$ make run
make -C ../min-initrd runU
make[1]: Entering directory '/home/shindom/unikernel/min-initrd'
taskset -c 0-15 qemu-system-x86_64 -cpu host -smp cpus=16 -m 30G -kernel ../linux/arch/x86/boot/bzImage -initrd min-initrd.d/initrd -hda min-initrd.d/root -nodefaults -nographic -serial stdio -append "console=ttyS0 root=/dev/sda nosmap mds=off ip=192.168.19.108:::255.255.255.0::eth0:none -u root -t 16 -m 16G -c 8192 -b 8192 -B binary" -netdev tap,id=vlan1,ifname=tap0,script=no,downscript=no,vhost=on,queues=16 -device virtio-net-pci,mq=on,vectors=33,netdev=vlan1,mac=02:00:00:04:00:29
qemu-system-x86_64: -hda min-initrd.d/root: Could not open 'min-initrd.d/root': No such file or directory
make[1]: *** [Makefile:72: runU] Error 1
make[1]: Leaving directory '/home/shindom/unikernel/min-initrd'
make: *** [Makefile:41: run] Error 2
$`

I tried to delete enable-kvm flag in the min-initrd/Makefile but I still have the same issue. I am running Fedora 32.

**Comment by razaaliraza** [comment]
You need to go to min-initrd directory and run make all first. We are working on better versions of UKL which dont have any of these issues and support a lot of different functionality. Cleaning up, will push soon.
